#version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_DATABASE: splitzyDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - splitzy_network


  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - splitzy_network


  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    ports:
      - "8080:8080"
      - "9092:9092"   # Expose the Socket.IO server port
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/splitzyDB
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_PROTOCOL: ${SPRING_MAIL_PROTOCOL}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    networks:
      - splitzy_network

networks:
  splitzy_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local