#version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_DATABASE: splitzyDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - splitzy_network


  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - splitzy_network


  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: splitzy
      POSTGRES_PASSWORD: splitzy
      POSTGRES_DB: splitzy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - splitzy_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@splitzy.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - splitzy_network

  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    ports:
      - "8080:8080"
      - "9092:9092"   # Expose the Socket.IO server port
    environment:
      # Force Postgres profile by default
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-postgres}
      # PostgreSQL
      POSTGRES_URL: jdbc:postgresql://postgres:5432/splitzy
      POSTGRES_USER: splitzy
      POSTGRES_PASSWORD: splitzy
      # Redis
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # Mail settings
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_PROTOCOL: ${SPRING_MAIL_PROTOCOL}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      # Google OAuth2 (must be explicitly passed for Spring to read)
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - splitzy_network

networks:
  splitzy_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  postgres_data:
    driver: local